"""Output formatters for analysis results."""

from __future__ import annotations

import csv
import io
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .models import AnalysisResult

__all__ = ["FORMAT_CHOICES", "format_output", "write_output"]

FORMAT_CHOICES = ("markdown", "csv", "html", "text")


def _to_text(result: AnalysisResult) -> str:
    lines = [
        "Website Analysis Report",
        "=" * 40,
        f"Generated: {result.timestamp}",
        f"Model: {result.model}",
        f"Focus: {result.focus}",
        f"Sites analyzed: {result.sites_analyzed}",
        "",
        "-" * 40,
        "",
        result.analysis,
    ]
    return "\n".join(lines)


def _to_csv(result: AnalysisResult) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["timestamp", "model", "focus", "sites_analyzed", "analysis"])
    writer.writerow([result.timestamp, result.model, result.focus, result.sites_analyzed, result.analysis])
    return output.getvalue()


def _to_html(result: AnalysisResult) -> str:
    import html as html_mod
    return (
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "<meta charset=\"utf-8\">\n"
        "<title>Website Analysis Report</title>\n"
        "<style>\n"
        "body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; }\n"
        "h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }\n"
        ".meta { color: #666; font-size: 0.9rem; }\n"
        ".analysis { white-space: pre-wrap; background: #f5f5f5; padding: 1rem; border-radius: 4px; }\n"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        f"<h1>Website Analysis Report</h1>\n"
        f"<p class=\"meta\">Generated: {html_mod.escape(result.timestamp)} | "
        f"Model: <code>{html_mod.escape(result.model)}</code> | "
        f"Focus: {html_mod.escape(result.focus)} | "
        f"Sites: {result.sites_analyzed}</p>\n"
        f"<div class=\"analysis\">{html_mod.escape(result.analysis)}</div>\n"
        "</body>\n"
        "</html>\n"
    )


def format_output(result: AnalysisResult, fmt: str = "markdown") -> str:
    """Format *result* as the requested output format."""
    if fmt == "markdown":
        return (
            f"# Website Analysis Report\n\n"
            f"**Generated:** {result.timestamp}  \n"
            f"**Model:** `{result.model}`  \n"
            f"**Focus:** {result.focus}  \n"
            f"**Sites:** {result.sites_analyzed}\n\n---\n\n{result.analysis}\n\n---\n*Generated by Protor*\n"
        )
    if fmt == "text":
        return _to_text(result)
    if fmt == "csv":
        return _to_csv(result)
    if fmt == "html":
        return _to_html(result)
    raise ValueError(f"Unknown format: {fmt!r}")


def write_output(result: AnalysisResult, output_dir: str | Path, fmt: str = "markdown") -> Path:
    """Write *result* to *output_dir* in the requested format."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    content = format_output(result, fmt)
    ext = {"markdown": "md", "text": "txt", "csv": "csv", "html": "html"}[fmt]
    filename = f"analysis.{ext}"
    path = out / filename
    path.write_text(content, encoding="utf-8")
    return path
