import os
from typing import Optional
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_ollama import OllamaLLM
from langchain_core.prompts import PromptTemplate
from rich.console import Console

console = Console()

ANALYSIS_PROMPTS = {
    "general": """
You are an AI analyst. Analyze the scraped website data and provide:
1. **Overview**: What is this website about?
2. **Key Content**: Main topics and themes
3. **Technical Stack**: Technologies detected
4. **Data Insights**: Interesting patterns or information
5. **Recommendations**: Potential use cases or improvements

Be concise and insightful.
""",
    "technical": """
You are a technical analyst. Focus on:
1. **Tech Stack**: Frontend/backend technologies detected
2. **JavaScript Analysis**: Frameworks, libraries, APIs used
3. **Performance**: Page structure and optimization opportunities
4. **Security**: Potential concerns or best practices
5. **Architecture**: Overall technical approach
""",
    "content": """
You are a content analyst. Focus on:
1. **Content Quality**: Writing style and clarity
2. **SEO Elements**: Titles, descriptions, keywords
3. **Structure**: Information hierarchy and organization
4. **Engagement**: Call-to-actions and user journey
5. **Audience**: Target demographic and tone
""",
    "seo": """
You are an SEO specialist. Analyze:
1. **Meta Tags**: Title, description, keywords quality
2. **Content Structure**: Headers, semantic HTML
3. **Technical SEO**: Page speed indicators, mobile-friendliness
4. **Improvements**: Specific SEO recommendations
5. **Competitive Edge**: Unique value propositions
"""
}

class RAGAnalyzer:
    def __init__(self, model: str = "llama3", focus: str = "general"):
        self.model = model
        self.focus = focus
        self.llm = OllamaLLM(model=model, base_url="http://localhost:11434")
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=2000,
            chunk_overlap=200,
            length_function=len,
        )
        
    def analyze_page(self, url: str, html_content: str, metadata: dict) -> str:
        """Analyze a single page using RAG approach"""
        try:
            # extract text content
            text_content = metadata.get('text_content', '')[:5000]  # Limit to 5000 chars
            
            # appropriate prompt
            analysis_prompt = ANALYSIS_PROMPTS.get(self.focus, ANALYSIS_PROMPTS["general"])
            
            # full prompt
            prompt_template = PromptTemplate(
                input_variables=["url", "title", "description", "content", "analysis_type"],
                template="""
{analysis_type}

## Website Information:
- **URL**: {url}
- **Title**: {title}
- **Description**: {description}

## Content Preview:
{content}

Provide your analysis in well-formatted Markdown:
"""
            )
            
            # the prompt
            formatted_prompt = prompt_template.format(
                url=url,
                title=metadata.get('metadata', {}).get('title', 'N/A'),
                description=metadata.get('metadata', {}).get('description', 'N/A'),
                content=text_content,
                analysis_type=analysis_prompt
            )
            
            # analysis from LLM
            console.print(f"[grey50]  ⟡ Analyzing with {self.model}...[/grey50]")
            result = self.llm.invoke(formatted_prompt)
            
            return result
            
        except Exception as e:
            console.print(f"[grey50]  ✗ Analysis failed: {e}[/grey50]")
            return f"# Analysis Failed\n\nError: {str(e)}"
    
    def save_analysis(self, output_path: str, url: str, analysis: str):
        """Save analysis to markdown file"""
        try:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            
            content = f"""# Website Analysis

**URL**: {url}  
**Model**: {self.model}  
**Focus**: {self.focus}  

---

{analysis}

---

*Generated by Protor RAG Analyzer*
"""
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
                
            console.print(f"[grey74]  ✓ Analysis saved:[/grey74] [grey50]{os.path.basename(output_path)}[/grey50]")
            
        except Exception as e:
            console.print(f"[grey50]  ✗ Failed to save analysis: {e}[/grey50]")
